name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests (demo-auth)
        if: ${{ github.repository == 'frknmydn/demo-auth' }}
        run: npm install jest supertest && npm run test --watch=false 
        
      - name: Trigger Notification Step
        if: ${{ github.repository == 'frknmydn/demo-auth' }}
        run: echo "Jest tests completed..."
        
